[tool.poetry]
name = "ore-concentrate"
version = "0.1.0"
description = ""
authors = ["vandersvan <vandersvan@gmail.com>"]
readme = "README.md"
packages = [{include = "ore_concentrate"}]

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
