"""add ore_concetrate and ore_concentrate_content models

Revision ID: ac9480a3e69d
Revises: 
Create Date: 2022-10-21 14:16:06.037210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac9480a3e69d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ore_concentrates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ore_concentrate_contents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('iron_percent', sa.Numeric(scale=6), nullable=True),
    sa.Column('silicon_percent', sa.Numeric(scale=6), nullable=True),
    sa.Column('aluminum_percent', sa.Numeric(scale=6), nullable=True),
    sa.Column('calcium_percent', sa.Numeric(scale=6), nullable=True),
    sa.Column('sulfur_percent', sa.Numeric(scale=6), nullable=True),
    sa.Column('ore_concentrate_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ore_concentrate_id'], ['ore_concentrates.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ore_concentrate_contents')
    op.drop_table('ore_concentrates')
    # ### end Alembic commands ###
